default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV["SUPABASE_DATABASE_URL"] %>

development:
  <<: *default
  database: sproutvault_be_development

test:
  <<: *default
  database: sproutvault_be_test

production:
  primary: &primary_production
    <<: *default
    database: sproutvault_be_production
    username: sproutvault_be
    password: <%= ENV["SPROUTVAULT_BE_DATABASE_PASSWORD"] %>
    url: <%= ENV["SUPABASE_DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: sproutvault_be_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sproutvault_be_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sproutvault_be_production_cable
    migrations_paths: db/cable_migrate
